# Generated by Django 4.2.4 on 2023-08-23 06:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bookshelf', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='authors',
            options={'ordering': ['name'], 'verbose_name': 'Автор', 'verbose_name_plural': 'Авторы'},
        ),
        migrations.AlterModelOptions(
            name='bookgenres',
            options={'ordering': ['book', 'genre'], 'verbose_name': 'Жанры книг', 'verbose_name_plural': 'Жанры книг'},
        ),
        migrations.AlterModelOptions(
            name='books',
            options={'ordering': ['author', 'name', 'date'], 'verbose_name': 'Книги', 'verbose_name_plural': 'Книги'},
        ),
        migrations.AlterModelOptions(
            name='countries',
            options={'ordering': ['name'], 'verbose_name': 'Страны', 'verbose_name_plural': 'Страны'},
        ),
        migrations.AlterModelOptions(
            name='genres',
            options={'ordering': ['name'], 'verbose_name': 'Жанр', 'verbose_name_plural': 'Жанры'},
        ),
        migrations.AlterModelOptions(
            name='languages',
            options={'ordering': ['name'], 'verbose_name': 'Языки', 'verbose_name_plural': 'Языки'},
        ),
        migrations.AlterModelOptions(
            name='notes',
            options={'ordering': ['book', 'user', 'par'], 'verbose_name': 'Заметка', 'verbose_name_plural': 'Заметки'},
        ),
        migrations.AlterModelOptions(
            name='paragraphs',
            options={'ordering': ['book', 'pk'], 'verbose_name': 'Абзац', 'verbose_name_plural': 'Абзацы книг'},
        ),
        migrations.AlterModelOptions(
            name='styles',
            options={'ordering': ['name'], 'verbose_name': 'Оформление', 'verbose_name_plural': 'Оформления'},
        ),
        migrations.AlterModelOptions(
            name='userdictionary',
            options={'ordering': ['user', 'original', 'book', 'par'], 'verbose_name': 'Словарик', 'verbose_name_plural': 'Переводы слов'},
        ),
        migrations.AlterModelOptions(
            name='userproperties',
            options={'ordering': ['user', 'style', 'book'], 'verbose_name': 'Настройка', 'verbose_name_plural': 'Настройки'},
        ),
        migrations.AlterModelOptions(
            name='users',
            options={'ordering': ['name'], 'verbose_name': 'Читатель', 'verbose_name_plural': 'Читатели'},
        ),
        migrations.RemoveField(
            model_name='notes',
            name='par_id',
        ),
        migrations.AddField(
            model_name='notes',
            name='par',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='bookshelf.paragraphs'),
        ),
        migrations.AddField(
            model_name='notes',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='bookshelf.users'),
        ),
        migrations.AddField(
            model_name='userdictionary',
            name='par',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='bookshelf.paragraphs'),
        ),
        migrations.AlterField(
            model_name='userdictionary',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='bookshelf.users'),
        ),
        migrations.AlterField(
            model_name='userproperties',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='bookshelf.users'),
        ),
    ]
